services:
  database:
    image: mysql:8.0
    container_name: nehemiah-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nehemiah_publishing
      MYSQL_USER: nehemiah_user
      MYSQL_PASSWORD: nehemiah_password
    ports:
      - "7306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nehemiah-network
    healthcheck:
      test:
        [
          "CMD",
          "mysql",
          "-h",
          "localhost",
          "-u",
          "root",
          "-prootpassword",
          "-e",
          "SELECT 1",
        ]
      timeout: 30s
      retries: 15
      interval: 10s
      start_period: 30s
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=128M --innodb-log-file-size=50M --innodb-flush-log-at-trx-commit=2 --innodb-flush-method=O_DIRECT

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nehemiah-backend
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DATABASE_URL: mysql://nehemiah_user:nehemiah_password@database:3306/nehemiah_publishing
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: nehemiah_user
      DB_PASSWORD: nehemiah_password
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      PORT: 5000
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "7001:5000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - nehemiah-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nehemiah-frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "8000:8000"
    depends_on:
      backend:
        condition: service_started
    networks:
      - nehemiah-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: nehemiah-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - nehemiah-network

volumes:
  mysql_data:
    driver: local

networks:
  nehemiah-network:
    driver: bridge
